#Define ccThorTool     'SideKick'

If 'O' # Vartype(_screen.oSKOptions) 
  m.loThor      = Execscript(_Screen.cThorDispatcher, 'Thor Engine=')
  loSk = CreateObject('empty')
  AddProperty(m.loSk, 'cDefaultCommand', m.loThor.GetOption('DefaultCommand',  ccThorTool))
  AddProperty(m.loSk, 'nFontsize', m.loThor.GetOption('Fontsize',  ccThorTool))
  AddProperty(m.loSk, 'lGridAuto', m.loThor.GetOption('GridAuto',  ccThorTool))
  AddProperty(m.loSk, 'lNewFirst', m.loThor.GetOption('NewFirst',  ccThorTool))
  AddProperty(m.loSk, 'nPathReturned', m.loThor.GetOption('PathReturned',  ccThorTool))
  AddProperty(m.loSk, 'nDisplayCase', m.loThor.GetOption('DisplayCase',  ccThorTool))
  AddProperty(m.loSk, 'cMRUTable', m.loThor.GetOption('MRUTable',  ccThorTool))
  AddProperty(m.loSk, 'lNewFirst', m.loThor.GetOption('NewFirst',  ccThorTool))
  AddProperty(m.loSk, 'nNextLength', m.loThor.GetOption('NextLength',  ccThorTool))
  AddProperty(m.loSk, 'cBackupFolder', m.loThor.GetOption('BackupFolder',  ccThorTool))
  AddProperty(m.loSk, 'cUnzipFolder', m.loThor.GetOption('UnzipFolder',  ccThorTool))
  AddProperty(m.loSk, 'cZipTarget', m.loThor.GetOption('ZipTarget',  ccThorTool))
  AddProperty(m.loSk, 'nZipDelay', m.loThor.GetOption('ZipDelay',  ccThorTool))
  AddProperty(m.loSk, 'cProject', m.loThor.GetOption('Project',  ccThorTool))
  AddProperty(m.loSk, 'cRunCommand', m.loThor.GetOption('RunCommand',  ccThorTool))
  AddProperty(m.loSk, 'nMaxDescriptLine', m.loThor.GetOption('MaxDescriptLine',  ccThorTool))
  AddProperty(m.loSk, 'cHelpURL', m.loThor.GetOption('HelpUrl',  ccThorTool))
  AddProperty(m.loSk, 'nWaitTimeout', m.loThor.GetOption('WaitTimeout',  ccThorTool))
  _screen.AddProperty('oSKOptions',m.loSk)
Endif
